allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

// Disable crashing lint detector in all Android subprojects (incl. file_picker)
subprojects {
    pluginManager.withPlugin('com.android.library') {
        android {
            lint {
                disable "NullSafeMutableLiveData"
                checkReleaseBuilds false
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
